import { expect, test } from '@playwright/test'
const path = '/apps/harness/tests/settings-fixture.html?page=memory'
const inspect = (page, name) => page.getByRole('button', { name: `Inspect ${name}`, exact: true })

test('memory actions lead without explanatory copy and browsing opens attributed evidence', async ({ page }) => {
  await page.goto(path)
  await expect(page.getByRole('button', { name: 'Add memory', exact: true })).toBeVisible()
  await expect(page.getByText(/Facts shared across conversations|The agent can save durable facts|How sharing works|Applies across conversations|Dreaming uses the LCM model|Original content stays searchable/)).toHaveCount(0)
  await expect(page.getByText('4 saved memories')).toBeVisible()
  await inspect(page, 'project-review').click()
  const editor = page.getByRole('form', { name: 'Edit project-review' })
  await expect(editor.getByRole('textbox', { name: 'Memory', exact: true })).toHaveValue(/Review changes/)
  await expect(editor.getByRole('link', { name: /Open conversation/ })).toHaveAttribute('href', '#daily-notes')
  await expect(editor.getByText(/Captured by ~zod/)).toBeVisible()
  await editor.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(inspect(page, 'project-review')).toBeFocused()
  await inspect(page, 'project-review').click()
  await inspect(page, 'project-review').click()
  await expect(editor).toHaveCount(0)
})

test('add, correct and forget preserve source history', async ({ page }) => {
  await page.goto(path)
  await page.getByRole('button', { name: 'Add memory', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toBeFocused()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('project-location')
  await page.getByRole('textbox', { name: 'Memory', exact: true }).fill('The project lives in the workshop.')
  await page.getByRole('button', { name: 'Save memory', exact: true }).click()
  await expect(page.getByText('5 saved memories')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add memory', exact: true })).toBeFocused()
  await inspect(page, 'project-review').click()
  await page.getByRole('textbox', { name: 'Memory', exact: true }).fill('Review changes with examples and test results.')
  await page.getByRole('button', { name: 'Save memory', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Add memory', exact: true })).toBeFocused()
  await inspect(page, 'project-review').click()
  await page.getByText('Recent revisions', { exact: true }).click()
  await expect(page.getByRole('link', { name: /Open conversation/ })).toBeVisible()
  await page.getByRole('button', { name: 'Forget memory', exact: true }).click()
  await expect(page.getByRole('group', { name: 'Confirm forgetting' })).toContainText('Source conversations and revision history stay available.')
  await page.getByRole('button', { name: 'Confirm forget', exact: true }).click()
  await expect(inspect(page, 'project-review')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Add memory', exact: true })).toBeFocused()
  const record = await page.evaluate(() => window.settingsFixture.getMemories().find(row => row.name === 'project-review'))
  expect(record.text).toBeNull()
  expect(record.history.at(-1).source.sessionId).toBe('daily-notes')
})

test('stale corrections retain drafts and reload explicitly', async ({ page }) => {
  await page.goto(path)
  await inspect(page, 'project-review').click()
  const body = page.getByRole('textbox', { name: 'Memory', exact: true })
  await body.fill('My correction stays visible.')
  await page.evaluate(() => { window.settingsFixture.getMemories().find(row => row.name === 'project-review').revision = '99' })
  await page.getByRole('button', { name: 'Save memory', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Memory changed')
  await expect(body).toHaveValue('My correction stays visible.')
  await page.getByRole('button', { name: 'Reload current memory' }).click()
  await expect(body).toHaveValue(/Review changes/)
  await body.fill('A considered correction.')
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(body).toBeHidden()
  await expect(inspect(page, 'project-review')).toContainText('Unsaved changes')
  await inspect(page, 'project-review').click()
  await expect(body).toHaveValue('A considered correction.')
})

test('search keeps the newest request and distinguishes empty results', async ({ page }) => {
  await page.goto(path)
  await page.evaluate(() => { window.settingsFixture.holdMemoryQuery = 'project' })
  const search = page.getByRole('searchbox', { name: 'Search memories' })
  await search.fill('project'); await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect.poll(() => page.evaluate(() => Boolean(window.settingsFixture.releaseMemoryQuery))).toBe(true)
  await search.fill('absent'); await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.getByText('No matching memories', { exact: true })).toBeVisible()
  await page.evaluate(() => window.settingsFixture.releaseMemoryQuery())
  await expect(page.locator('.memory-row')).toHaveCount(0)
  await expect(page.getByText('Results for “absent”')).toBeVisible()
  await page.getByRole('button', { name: 'Clear search' }).click()
  await expect(page.locator('.memory-row')).toHaveCount(4)
})

test('pagination, retry and empty state are usable', async ({ page }) => {
  await page.goto(`${path}&many-memories`)
  await expect(page.locator('.memory-row')).toHaveCount(25)
  await page.evaluate(() => { window.settingsFixture.failMemoryOperation = 'list' })
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Memory service unavailable')
  await expect(page.locator('.memory-row')).toHaveCount(25)
  await inspect(page, 'fact-0').click()
  await expect(page.getByRole('button', { name: 'Retry loading memories' })).toBeDisabled()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.evaluate(() => { window.settingsFixture.failMemoryOperation = null })
  await page.getByRole('button', { name: 'Retry loading memories' }).click()
  await expect(page.locator('.memory-row')).toHaveCount(5)
  await expect(page.getByText('Page 2 · 5 shown')).toBeVisible()
  await expect(page.locator('.memory-list-heading')).toBeFocused()
  await page.getByRole('button', { name: 'Previous', exact: true }).click()
  await expect(page.locator('.memory-row')).toHaveCount(25)
  await expect(page.getByText('Page 1 · 25 shown')).toBeVisible()
  await page.goto(`${path}&empty-memories`)
  await expect(page.getByText('Nothing remembered yet')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add memory', exact: true })).toBeEnabled()
})

test('pending page replacement cannot remove a newly opened editor', async ({ page }) => {
  await page.goto(`${path}&many-memories`)
  await expect(page.locator('.memory-row')).toHaveCount(25)
  await page.evaluate(() => { window.settingsFixture.holdMemoryQuery = '' })
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect.poll(() => page.evaluate(() => Boolean(window.settingsFixture.releaseMemoryQuery))).toBe(true)
  await expect(inspect(page, 'fact-0')).toBeDisabled()
  await expect(page.getByRole('form', { name: 'Edit fact-0' })).toHaveCount(0)
  await page.evaluate(() => window.settingsFixture.releaseMemoryQuery())
  await expect(page.locator('.memory-row')).toHaveCount(5)
  await inspect(page, 'fact-25').click()
  await page.getByRole('textbox', { name: 'Memory', exact: true }).fill('This draft stays attached to its record.')
  await inspect(page, 'fact-25').click()
  await inspect(page, 'fact-25').click()
  await expect(page.getByRole('textbox', { name: 'Memory', exact: true })).toHaveValue('This draft stays attached to its record.')
})

test('UTF-8 limits and mobile forms protect edits', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(path)
  await page.getByRole('button', { name: 'Add memory', exact: true }).click()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('test-memory')
  await page.getByRole('textbox', { name: 'Memory', exact: true }).fill('界'.repeat(350))
  await expect(page.getByRole('button', { name: 'Save memory', exact: true })).toBeDisabled()
  await expect(page.getByText('1,050 / 1,024 bytes')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('a preference draft collapses, resumes and discards on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(path)
  await inspect(page, 'project-review').click()
  const editor = page.getByRole('form', { name: 'Edit project-review' })
  const preference = editor.getByRole('checkbox', { name: /Use across topics/ })
  await preference.check()
  await inspect(page, 'project-review').click()
  await expect(editor).toBeHidden()
  await expect(inspect(page, 'project-review')).toHaveAttribute('aria-expanded', 'false')
  await expect(inspect(page, 'project-review')).toContainText('Unsaved changes')
  await inspect(page, 'project-review').click()
  await expect(preference).toBeChecked()
  await editor.getByRole('button', { name: 'Save memory', exact: true }).click()
  await inspect(page, 'project-review').click()
  await expect(preference).toBeChecked()
  await preference.uncheck()
  await editor.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Add memory', exact: true })).toBeEnabled()
  await inspect(page, 'project-review').click()
  await expect(preference).toBeChecked()
})
