import { expect, test } from '@playwright/test'

test('Peers is reachable from settings and trusted ships start unlimited', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=shell&global')
  await page.getByRole('button', { name: 'Peers', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Incoming peer access' })).toBeVisible()
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' })).toHaveValue('0')
  await expect(page.getByText(/0 = unlimited/).first()).toBeVisible()
  await expect(page.getByRole('checkbox', { name: /Use global defaults/ })).toBeChecked()
})

test('explicit peer grants can be added, capped, reloaded and revoked', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers')
  const picker = page.getByRole('combobox', { name: 'Add a peer ship' })
  await picker.fill('~lux')
  await picker.press('Enter')
  await page.locator('summary').filter({ hasText: '~lux' }).click()
  const limit = page.getByRole('spinbutton', { name: 'Peer token limit for ~lux' })
  await expect(limit).toHaveValue('0')
  await limit.fill('25000')
  await page.getByRole('button', { name: 'Save peer settings', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Peer settings saved.')
  await page.reload()
  await page.locator('summary').filter({ hasText: '~lux' }).click()
  await expect(limit).toHaveValue('25000')
  await page.getByRole('button', { name: 'Revoke ~lux', exact: true }).click()
  await page.getByRole('button', { name: 'Save peer settings', exact: true }).click()
  await expect(page.locator('summary').filter({ hasText: '~lux' })).toHaveCount(0)
})

test('Tlon trusted ships expose the same peer limit and preserve it after reload', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=tlon')
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  const limit = page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' })
  await expect(limit).toHaveValue('0')
  await expect(limit).toBeEnabled()
  await limit.fill('10000')
  await page.getByRole('button', { name: 'Save Tlon settings' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1)?.peers?.limits.find((entry) => entry.ship === '~nec')?.budget)).toBe(10000)
  await page.reload()
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  await expect(limit).toHaveValue('10000')
  await limit.fill('0')
  await page.getByRole('button', { name: 'Save Tlon settings' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1)?.peers?.limits.find((entry) => entry.ship === '~nec')?.budget)).toBe(0)
})

test('failed peer limit saves keep the draft and report the partial Tlon save', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=tlon')
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  const limit = page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' })
  await expect(limit).toBeEnabled()
  await limit.fill('7500')
  await page.evaluate(() => { window.settingsFixture.failPeerSave = true })
  await page.getByRole('button', { name: 'Save Tlon settings' }).click()
  await expect(page.getByRole('alert').first()).toContainText('Tlon trust saved, but peer token limits were not saved')
  await expect(limit).toHaveValue('7500')
})

test('peer load errors do not expose an editable fallback policy', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers')
  await page.evaluate(() => { window.settingsFixture.failPeerRead = true })
  await expect(page.getByRole('alert')).toContainText('Peer settings unavailable')
  await expect(page.getByRole('button', { name: 'Save peer settings', exact: true })).toBeDisabled()
  await expect(page.getByRole('combobox', { name: 'Add a peer ship' })).toBeDisabled()
})
