import { expect, test } from '@playwright/test'

for (const surface of ['peers', 'tlon']) {
  test(`${surface}: grant all fills the draft and saves current resources without changing limits`, async ({ page }) => {
    await page.addInitScript(() => sessionStorage.setItem('settings-fixture-skills', JSON.stringify([{ name: 'checklist', desc: 'Make a checklist' }])))
    await page.goto(`/apps/harness/tests/settings-fixture.html?page=${surface}&all-permissions`)
    await page.locator('summary').filter({ hasText: '~nec' }).click()
    if (surface === 'peers') await page.getByRole('textbox', { name: 'Model override for ~nec' }).fill('custom-model')
    await page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' }).fill('500')
    const bulk = page.getByRole('button', { name: 'Grant all available to ~nec' })
    await bulk.click()
    await expect(bulk).toHaveText('All available selected')
    await expect(bulk).toBeDisabled()
    await expect(page.getByRole('checkbox', { name: /All Clay files/ })).toBeChecked()
    await expect(page.getByRole('checkbox', { name: /MCP: Calendar/ })).toBeChecked()
    await expect(page.getByRole('checkbox', { name: /MCP: Disabled/ })).not.toBeChecked()
    await expect(page.getByRole('checkbox', { name: /Cross-conversation recall/ })).toHaveCount(0)
    expect(await page.evaluate(() => window.settingsFixture.saves)).toEqual([])
    await page.getByRole('button', { name: surface === 'peers' ? 'Save peer settings' : 'Save Tlon settings', exact: true }).click()
    await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.length)).toBe(surface === 'peers' ? 1 : 2)
    const saves = await page.evaluate(() => window.settingsFixture.saves)
    const grant = surface === 'peers' ? saves[0].peers.grants.find(row => row.ship === '~nec') : saves[0].tlon.trusted.find(row => row.ship === '~nec')
    expect(grant.tools).toEqual(expect.arrayContaining(['web', 'curl', 'code', 'workspace', 'skills', 'subagents', 'peers', 'tlon', { clay: '/' }, { mcp: 'calendar' }, { mcp: 'notes' }]))
    expect(grant.tools).not.toEqual(expect.arrayContaining(['admin']))
    if (surface === 'peers') {
      expect(grant).toMatchObject({ budget: 500, model: 'custom-model', inflows: ['checklist'] })
    } else {
      expect(saves[1].peers.limits).toEqual([{ ship: '~nec', budget: 500 }])
    }
    await page.reload()
    await page.locator('summary').filter({ hasText: '~nec' }).click()
    await expect(bulk).toHaveText('All available selected')
    await page.getByRole('checkbox', { name: /Web search & GET/ }).uncheck()
    await expect(bulk).toBeEnabled()
  })
}

test('grant all waits for catalogs and recovers from a failed MCP read', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers&hold-tools&fail-mcp')
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  const bulk = page.getByRole('button', { name: 'Grant all available to ~nec' })
  await expect(bulk).toBeDisabled()
  await page.evaluate(() => window.settingsFixture.releaseTools())
  await expect(page.getByText('Permission catalog unavailable.')).toBeVisible()
  await expect(bulk).toBeDisabled()
  await page.evaluate(() => { window.settingsFixture.retryMcp = true })
  await page.getByRole('button', { name: 'Retry loading permissions' }).click()
  await expect(bulk).toBeEnabled()
})

for (const width of [1440, 390]) {
  test(`peer model field stays compact at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/apps/harness/tests/settings-fixture.html?page=peers')
    await page.locator('summary').filter({ hasText: '~nec' }).click()
    const model = await page.getByRole('textbox', { name: 'Model override for ~nec' }).boundingBox()
    const limit = await page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' }).boundingBox()
    expect(model.height).toBeLessThanOrEqual(44)
    expect(model.height).toBe(limit.height)
    if (width > 760) expect(model.y).toBe(limit.y)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  })
}

test('ownership uses a light read and contacts are shared without rapid settings polling', async ({ page }) => {
  await page.clock.install()
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers')
  await expect(page.getByRole('combobox', { name: 'Owner ship' })).toHaveValue('~bud')
  const reads = () => page.evaluate(() => window.settingsFixture.reads)
  const initial = await reads()
  expect(initial).toContain('tlon/owner')
  expect(initial).not.toContain('tlon')
  expect(initial.filter((path) => path === 'tlon/contacts')).toHaveLength(1)
  await page.clock.fastForward(10_000)
  const after = await reads()
  for (const path of ['tlon/owner', 'tlon/contacts', 'defaults', 'tools', 'mcp', 'peers']) {
    expect(after.filter((read) => read === path)).toHaveLength(1)
  }
})

test('Peers is reachable from settings and trusted ships start unlimited', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=shell&global')
  await page.getByRole('button', { name: 'Peers', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Incoming peer access' })).toBeVisible()
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' })).toHaveValue('0')
  await expect(page.getByText(/0 = unlimited/).first()).toBeVisible()
  await expect(page.getByRole('checkbox', { name: /Use global defaults/ })).toBeChecked()
})

test('explicit peer grants can be added, capped, reloaded and revoked', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers')
  const picker = page.getByRole('combobox', { name: 'Add a peer ship' })
  await picker.fill('~lux')
  await picker.press('Enter')
  await page.locator('summary').filter({ hasText: '~lux' }).click()
  const limit = page.getByRole('spinbutton', { name: 'Peer token limit for ~lux' })
  await expect(limit).toHaveValue('0')
  await limit.fill('25000')
  await page.getByRole('button', { name: 'Save peer settings', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Peer settings saved.' })).toBeVisible()
  await page.reload()
  await page.locator('summary').filter({ hasText: '~lux' }).click()
  await expect(limit).toHaveValue('25000')
  await page.getByRole('button', { name: 'Revoke ~lux', exact: true }).click()
  await page.getByRole('button', { name: 'Save peer settings', exact: true }).click()
  await expect(page.locator('summary').filter({ hasText: '~lux' })).toHaveCount(0)
})

test('Tlon trusted ships expose the same peer limit and preserve it after reload', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=tlon')
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  const limit = page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' })
  await expect(limit).toHaveValue('0')
  await expect(limit).toBeEnabled()
  await limit.fill('10000')
  await page.getByRole('button', { name: 'Save Tlon settings' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1)?.peers?.limits.find((entry) => entry.ship === '~nec')?.budget)).toBe(10000)
  await page.reload()
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  await expect(limit).toHaveValue('10000')
  await limit.fill('0')
  await page.getByRole('button', { name: 'Save Tlon settings' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1)?.peers?.limits.find((entry) => entry.ship === '~nec')?.budget)).toBe(0)
})

test('failed peer limit saves keep the draft and report the partial Tlon save', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=tlon')
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  const limit = page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' })
  await expect(limit).toBeEnabled()
  await limit.fill('7500')
  await page.evaluate(() => { window.settingsFixture.failPeerSave = true })
  await page.getByRole('button', { name: 'Save Tlon settings' }).click()
  await expect(page.getByRole('alert').first()).toContainText('Tlon trust saved, but peer token limits were not saved')
  await expect(limit).toHaveValue('7500')
})

test('peer load errors do not expose an editable fallback policy', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers')
  await page.evaluate(() => { window.settingsFixture.failPeerRead = true })
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(page.getByRole('alert')).toContainText('Peer settings unavailable')
  await expect(page.getByRole('button', { name: 'Save peer settings', exact: true })).toBeDisabled()
  await expect(page.getByRole('combobox', { name: 'Add a peer ship' })).toBeDisabled()
})

for (const surface of ['peers', 'tlon']) test(`${surface} resets recorded usage without saving a draft limit`, async ({ page }) => {
  await page.goto(`/apps/harness/tests/settings-fixture.html?page=${surface}`)
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  const limit = page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' })
  await expect(page.getByText('1,234 tokens used', { exact: true })).toBeVisible()
  await limit.fill('9000')
  const reset = page.getByRole('button', { name: 'Reset token count for ~nec' })
  await reset.click()
  await expect(page.getByText('0 tokens used · Count reset.', { exact: true })).toBeVisible()
  await expect(reset).toBeDisabled()
  await expect(limit).toHaveValue('9000')
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.map((action) => Object.keys(action)[0]))).toEqual(['peerReset'])
  await page.reload()
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  await expect(page.getByText('0 tokens used', { exact: true })).toBeVisible()
  await expect(limit).toHaveValue('0')
})

test('failed token resets preserve usage and offer a retry', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers')
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  await page.evaluate(() => { window.settingsFixture.failPeerReset = true })
  await page.getByRole('button', { name: 'Reset token count for ~nec' }).click()
  await expect(page.getByRole('alert')).toContainText('Could not reset token count')
  await expect(page.getByText('1,234 tokens used', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Reset token count for ~nec' })).toBeEnabled()
})

test('owners are full admins and optional sibling access survives reload', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers&moon')
  await expect(page.getByRole('heading', { name: 'Owner · full admin' })).toBeVisible()
  await page.locator('summary').filter({ hasText: '~bud' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Peer token limit for ~bud' })).toHaveCount(0)
  const siblings = page.getByRole('checkbox', { name: /Make sibling moons full admins/ })
  await expect(siblings).not.toBeChecked()
  await siblings.check()
  await page.getByRole('button', { name: 'Save ownership' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Ownership saved.' })).toBeVisible()
  await page.reload()
  await expect(siblings).toBeChecked()
  await siblings.uncheck()
  await page.getByRole('button', { name: 'Clear owner', exact: true }).click()
  await page.getByRole('button', { name: 'Save ownership' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Ownership saved.' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Owner ship', exact: true })).toHaveValue('')
})

test('remote permission checks never create incoming grants', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers')
  const picker = page.getByRole('combobox', { name: 'Check access on a ship' })
  await picker.fill('~lux'); await picker.press('Enter')
  await expect(page.locator('summary').filter({ hasText: '~lux' })).toContainText('Access reported')
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves)).toEqual([{ peerCheck: '~lux' }])
  await expect(page.getByRole('spinbutton', { name: 'Peer token limit for ~lux' })).toHaveCount(0)
})

test('ownership updates remain visible while peer edits are unsaved', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=peers')
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  await page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' }).fill('500')
  const owner = page.getByRole('combobox', { name: 'Owner ship', exact: true })
  await owner.fill('~nec'); await owner.press('Enter')
  await page.getByRole('button', { name: 'Save ownership' }).click()
  await expect(page.locator('summary').filter({ hasText: '~nec' })).toContainText('Owner · full admin')
  await expect(page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' })).toHaveCount(0)
  await expect(page.locator('summary').filter({ hasText: '~bud' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Save peer settings', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('reload before saving')
})

test('Tlon trusted owners do not offer ineffective peer limits', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=tlon&trusted-owner')
  await page.locator('summary').filter({ hasText: '~nec' }).click()
  await expect(page.locator('summary').filter({ hasText: '~nec' })).toContainText('Owner · full admin')
  await expect(page.getByRole('spinbutton', { name: 'Peer token limit for ~nec' })).toHaveCount(0)
  await expect(page.getByText(/Owners have no peer token cap/)).toBeVisible()
})
