import { expect, test } from '@playwright/test'

test('phone navigation exposes names and search, restores focus, and closes on selection', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/apps/harness/tests/fixture.html?many')
  const trigger = page.getByRole('button', { name: 'Open navigation' })
  await trigger.click()
  const drawer = page.getByRole('dialog', { name: 'Navigation' })
  await expect(drawer).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('navigation.png') })
  await page.keyboard.press('Escape')
  await expect(drawer).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  const search = drawer.getByRole('searchbox', { name: 'Search conversations' })
  await search.fill('conversation-45')
  await drawer.getByRole('button', { name: 'conversation-45', exact: true }).click()
  await expect(drawer).not.toBeVisible()
  await expect(page.locator('.chat-heading strong')).toHaveText('conversation-45')
  await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeInViewport()
  await trigger.click()
  await page.setViewportSize({ width: 1280, height: 900 })
  await expect(page.getByRole('dialog', { name: 'Navigation' })).toHaveCount(0)
  await expect(page.getByRole('searchbox', { name: 'Search conversations' })).toBeVisible()
})

for (const width of [390, 768, 1280]) for (const colorScheme of ['light', 'dark']) {
  test(`settings and Tlon remain usable at ${width}px in ${colorScheme}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 844 })
    await page.emulateMedia({ colorScheme })
    await page.goto('/apps/harness/tests/settings-fixture.html?page=shell&global')
    await expect(page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button')).toHaveText(['Defaults', 'Providers', 'Skills', 'MCP', 'Search'])
    await page.goto('/apps/harness/tests/settings-fixture.html?page=shell')
    await expect(page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button')).toHaveText(['Conversation', 'Providers', 'Defaults', 'Skills', 'MCP', 'Search'])
    await page.getByRole('button', { name: 'Providers', exact: true }).click()
    await page.getByRole('button', { name: 'OpenAI', exact: true }).click()
    await expect(page.getByLabel('Authentication')).toBeVisible()
    await expect(page.getByRole('button', { name: 'OpenAI', exact: true })).toHaveAttribute('aria-current', 'page')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath('settings.png'), fullPage: true })
    await page.goto('/apps/harness/tests/tlon-fixture.html')
    await expect(page.getByRole('heading', { name: 'Connection', exact: true })).toBeInViewport()
    await expect(page.getByLabel('Owner ship')).toBeVisible()
    expect(await page.evaluate(() => window.tlonFixture.workReads)).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath('tlon.png'), fullPage: true })
  })
}

for (const width of [390, 1280]) test(`settings actions and path controls align at ${width}px`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 844 })
  await page.emulateMedia({ colorScheme: width === 390 ? 'dark' : 'light' })
  await page.goto('/apps/harness/tests/settings-fixture.html?page=shell')
  const field = page.getByLabel('Clay read path')
  await field.fill('/harness/lib')
  await expect(page.getByRole('button', { name: 'Grant Clay path' })).toBeVisible()
  const pathBounds = await page.locator('.tool-path-grant').boundingBox()
  const groupBounds = await page.locator('.tool-options').boundingBox()
  expect(Math.abs(pathBounds.width - groupBounds.width)).toBeLessThan(1)
  await page.screenshot({ path: testInfo.outputPath('tools-layout.png') })
  await page.goto('/apps/harness/tests/settings-fixture.html?page=mcp')
  await expect(page.getByText('No MCP servers configured')).toBeVisible()
  await page.getByRole('button', { name: 'Add server', exact: true }).click()
  await page.getByRole('button', { name: 'Add header', exact: true }).click()
  await page.getByLabel('Header name').fill('authorization')
  await page.getByLabel('Header value').fill('fixture-token')
  const remove = page.getByRole('button', { name: 'Remove header' })
  await expect(remove).toBeVisible()
  if (width === 390) expect((await remove.boundingBox()).width).toBeGreaterThanOrEqual(44)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('mcp-layout.png'), fullPage: true })
  await remove.click()
  await expect(page.getByLabel('Header value')).toHaveCount(0)
})
