import { expect, test } from '@playwright/test'

for (const surface of ['global', 'conversation']) for (const width of [390, 1280]) {
  test(`${surface} save feedback follows edits and theme changes immediately at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 844 })
    await page.goto(`/apps/harness/tests/settings-fixture.html?page=${surface}`)
    const save = page.getByRole('button', { name: surface === 'global' ? 'Save defaults' : 'Save conversation' })
    const status = page.locator('.save-bar').getByRole('status')
    await save.click()
    await expect(status).toHaveText('Saved.')
    await page.getByLabel('Model', { exact: true }).fill('changed-model')
    await expect(status).toContainText('Unsaved changes')
    await save.click()
    await expect(status).toHaveText('Saved.')
    await page.getByRole('combobox', { name: 'Provider', exact: true }).selectOption('openai')
    await expect(status).toContainText('Unsaved changes')
    await save.click()
    await page.getByLabel('Authentication').selectOption('device')
    await expect(status).toContainText('Unsaved changes')
    await page.getByLabel('System instructions', { exact: true }).fill('Keep my revised instructions.')
    await page.evaluate(() => { window.settingsFixture.failSave = true })
    await save.click()
    await expect(page.getByRole('alert')).toContainText('Configuration save failed')
    await expect(page.getByLabel('System instructions', { exact: true })).toHaveValue('Keep my revised instructions.')
    await expect(status).toContainText('Unsaved changes')
    await page.evaluate(() => { window.settingsFixture.failSave = false })
    await save.click()
    await expect(status).toHaveText('Saved.')
    await expect(page.getByRole('alert')).toHaveCount(0)
    const count = await page.evaluate(() => window.settingsFixture.saves.length)
    const theme = page.getByRole('group', { name: 'Color theme' })
    await expect(theme.getByRole('button', { name: 'system', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await theme.getByRole('button', { name: width === 390 ? 'dark' : 'light', exact: true }).click()
    await expect(theme.getByRole('button', { pressed: true })).toHaveText(width === 390 ? 'dark' : 'light')
    await expect(page.locator('html')).toHaveAttribute('data-theme', width === 390 ? 'dark' : 'light')
    expect(await page.evaluate(() => window.settingsFixture.saves.length)).toBe(count)
    await expect(status).toHaveText('Saved.')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath('appearance-feedback.png') })
  })
}

test('replacing a provider key clears the old save confirmation', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=provider')
  await page.getByLabel('API key', { exact: true }).fill('fixture-first-key')
  await page.getByRole('button', { name: 'Save OpenAI' }).click()
  const status = page.locator('.save-bar').getByRole('status')
  await expect(status).toHaveText('Saved.')
  await page.getByLabel('API key', { exact: true }).fill('fixture-replacement-key')
  await expect(status).not.toHaveText('Saved.')
})

test('search credential feedback does not claim unsaved provider changes were saved', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/apps/harness/tests/settings-fixture.html?page=search')
  await page.getByRole('combobox', { name: 'Search provider', exact: true }).selectOption('searxng')
  await page.getByLabel('SearXNG instance URL').fill('https://search.example.org')
  await page.getByLabel('Brave Search API key').fill('fixture-brave-key')
  await page.getByRole('button', { name: 'Save search key', exact: true }).click()
  await expect(page.getByText('Search key saved.', { exact: true })).toBeVisible()
  const status = page.locator('.save-bar').getByRole('status')
  await expect(status).toHaveText('Unsaved search provider changes.')
  expect(await page.evaluate(() => window.settingsFixture.saves)).toEqual([])
  await page.getByRole('button', { name: 'Save search provider' }).click()
  await expect(status).toHaveText('Search provider saved.')
  await page.getByLabel('Brave Search API key').fill('fixture-replacement-key')
  await expect(page.getByText('Search key saved.', { exact: true })).toHaveCount(0)
  await expect(status).toHaveText('Search provider saved.')
  await page.getByRole('button', { name: 'Remove search key' }).click()
  await expect(page.getByText('Search key removed.', { exact: true })).toBeVisible()
  await expect(status).toHaveText('Search provider saved.')
  await page.screenshot({ path: testInfo.outputPath('search-feedback.png') })
})
