import { chooseOption } from './picker'
import { expect, test } from '@playwright/test'
import { PROVIDERS } from '../src/providers.js'
import { defaultConfig } from '../src/defaults.js'

test.beforeEach(async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html')
  await expect.poll(() => page.evaluate(() => window.settingsFixture?.requests.length || 0)).toBeGreaterThan(0)
})

test('OpenAI is first and device login is the fresh default while saved API routes stay selected', async ({ page }) => {
  const provider = page.getByRole('combobox', { name: 'Provider', exact: true })
  await expect(provider).toHaveText('OpenAI')
  await provider.click()
  await expect(page.getByRole('option').first()).toHaveText('OpenAI')
  await provider.press('Escape')
  await page.goto('/apps/harness/tests/settings-fixture.html?page=provider')
  const auth = page.getByRole('combobox', { name: 'Authentication', exact: true })
  await expect(auth).toHaveText('Device login (ChatGPT)')
  await expect(page.getByRole('button', { name: 'Sign in with device code' })).toBeVisible()
  await auth.click()
  await expect(page.getByRole('option').first()).toHaveText('Device login (ChatGPT)')
  await auth.press('Escape')
  await page.evaluate(config => sessionStorage.setItem('settings-fixture-config', JSON.stringify(config)), defaultConfig({ url: PROVIDERS.openai.endpoint }))
  await page.reload()
  await expect(auth).toHaveText('API key')
  await expect(page.getByLabel('API key', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => window.settingsFixture.saves)).toEqual([])
})

for (const surface of ['global', 'conversation']) test(`${surface}: Tlon is a default, independently removable cross-conversation grant`, async ({ page }) => {
  await page.goto(`/apps/harness/tests/settings-fixture.html?page=${surface}`)
  const tool = page.getByRole('checkbox', { name: /^Tlon Read and send messages/ })
  await expect(tool).toBeChecked()
  await expect(page.getByText(/Includes editing, deletion, public publishing and persistent channel hooks beyond this conversation/)).toBeVisible()
  await tool.uncheck()
  await page.getByRole('button', { name: surface === 'global' ? 'Save defaults' : 'Save conversation' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1)?.tools)).toEqual(defaultConfig().tools.filter((grant) => grant !== 'tlon'))
  await page.reload()
  await expect(tool).not.toBeChecked()
})

test('context is read from the catalog at save time, even when metadata arrives after selection', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?hold-models')
  await expect.poll(() => page.evaluate(() => window.settingsFixture.requests.length)).toBeGreaterThan(0)
  await expect(page.getByRole('spinbutton')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Model', exact: true }).fill('test-model')
  await page.evaluate(() => {
    const f = window.settingsFixture
    f.resolve(f.requests.at(-1).id, { modelInfo: [{ id: 'test-model', contextWindow: 32768 }] })
  })
  await expect(page.getByText(/Provider reports 32,768/)).toBeVisible()
  await page.getByRole('button', { name: 'Save defaults' }).click()
  expect(await page.evaluate(() => window.settingsFixture.saves.at(-1)['max-context'])).toBe(32768)
})

for (const surface of ['global', 'conversation']) test(`${surface}: default grants and explicit opt-ins and opt-outs survive reload`, async ({ page }) => {
  await page.goto(`/apps/harness/tests/settings-fixture.html?page=${surface}`)
  await expect(page.getByRole('checkbox', { name: /^Web search & GET/ })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: /^Skills Read instructions/ })).toBeChecked()
  const authoring = page.getByRole('checkbox', { name: /^Skill experiments/ })
  await expect(authoring).toBeChecked()
  await expect(page.getByRole('checkbox', { name: /^Write shared skills/ })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: /^MCP: Calendar/ })).not.toBeChecked()
  await expect(page.getByRole('button', { name: 'Enable all' })).toHaveCount(0)
  await authoring.uncheck()
  await page.getByRole('checkbox', { name: /^MCP: Calendar/ }).check()
  await page.getByRole('button', { name: surface === 'global' ? 'Save defaults' : 'Save conversation' }).click()
  const tools = defaultConfig().tools.filter((grant) => grant !== 'author')
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1)?.tools)).toEqual([...tools, { mcp: 'calendar' }])
  await page.reload()
  await expect(authoring).not.toBeChecked()
  await expect(page.getByRole('checkbox', { name: /^MCP: Calendar/ })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: /^MCP: Notes/ })).not.toBeChecked()
  await page.getByRole('checkbox', { name: /^MCP: Calendar/ }).uncheck()
  await page.getByRole('button', { name: surface === 'global' ? 'Save defaults' : 'Save conversation' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1)?.tools)).toEqual(tools)
})

for (const surface of ['global', 'conversation']) test(`${surface}: Clay grants name paths and survive reload independently of MCP`, async ({ page }) => {
  await page.goto(`/apps/harness/tests/settings-fixture.html?page=${surface}`)
  await page.getByLabel('Clay read path').fill('/harness/lib')
  await page.getByRole('button', { name: 'Grant Clay path' }).click()
  await expect(page.getByRole('checkbox', { name: /^Clay: \/harness\/lib/ })).toBeChecked()
  await page.getByRole('checkbox', { name: /^MCP: Calendar/ }).check()
  const save = () => page.getByRole('button', { name: surface === 'global' ? 'Save defaults' : 'Save conversation' }).click()
  await save()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: /^Clay: \/harness\/lib/ })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: /^MCP: Calendar/ })).toBeChecked()
  await page.getByRole('checkbox', { name: /^Clay: \/harness\/lib/ }).click()
  await expect(page.getByRole('checkbox', { name: /^Clay: \/harness\/lib/ })).toHaveCount(0)
  await save()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1).tools)).toEqual([...defaultConfig().tools, { mcp: 'calendar' }])
})

test('search key can be configured, survives reload, and can be removed', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=search')
  await expect(page.getByText('key needed', { exact: true })).toBeVisible()
  await page.getByLabel('Brave Search API key').fill('fixture-brave-key')
  await page.getByRole('button', { name: 'Save search key' }).click()
  await expect(page.getByText('key configured', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Brave Search API key')).toHaveValue('')
  await page.reload()
  await expect(page.getByText('key configured', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Remove search key' }).click()
  await expect(page.getByText('key needed', { exact: true })).toBeVisible()
})

test('SearXNG selection persists without removing the Brave key', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=search')
  await page.getByLabel('Brave Search API key').fill('fixture-brave-key')
  await page.getByRole('button', { name: 'Save search key' }).click()
  await chooseOption(page.getByRole('combobox', { name: 'Search provider', exact: true }), 'searxng')
  await page.getByLabel('SearXNG instance URL').fill('https://search.example.org/prefix/')
  await page.getByRole('button', { name: 'Save search provider' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1))).toEqual({ provider: 'searxng', 'instance-url': 'https://search.example.org/prefix' })
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Search provider', exact: true })).toHaveText('SearXNG')
  await expect(page.getByLabel('SearXNG instance URL')).toHaveValue('https://search.example.org/prefix')
  await expect(page.getByText('key configured', { exact: true })).toBeVisible()
  await chooseOption(page.getByRole('combobox', { name: 'Search provider', exact: true }), 'brave')
  await page.getByRole('button', { name: 'Save search provider' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1).provider)).toBe('brave')
})

test('MCP ids keep focus while typing and row removal preserves remaining headers', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?page=mcp')
  const add = page.getByRole('button', { name: 'Add server', exact: true })
  const save = page.getByRole('button', { name: 'Save MCP servers' })
  await add.click()
  await page.getByLabel('Server id').pressSequentially('first-server')
  await expect(page.getByLabel('Server id')).toHaveValue('first-server')
  await expect(page.getByLabel('Server id')).toBeFocused()
  await page.getByLabel('Server URL').fill('https://first.example/mcp')
  await save.click()
  await expect(page.getByText('Saved.', { exact: true })).toBeVisible()
  await add.click()
  await expect(page.getByText('Saved.', { exact: true })).toHaveCount(0)
  const second = page.locator('.mcp-server').nth(1)
  await second.getByLabel('Server id').pressSequentially('second-server')
  await second.getByLabel('Server URL').fill('https://second.example/mcp')
  await second.getByRole('button', { name: 'Add header' }).click()
  await second.getByLabel('Header name').fill('authorization')
  await second.getByLabel('Header value').fill('fixture-token')
  await save.click()
  await expect(page.getByText('Saved.', { exact: true })).toBeVisible()
  await page.locator('.mcp-server').first().getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(page.getByText('Saved.', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Server id')).toHaveValue('second-server')
  await expect(page.getByLabel('Header value')).toHaveValue('fixture-token')
  await save.click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1))).toEqual([
    { id: 'second-server', name: 'second-server', url: 'https://second.example/mcp', enabled: true, headers: [{ name: 'authorization', value: 'fixture-token' }] },
  ])
})

test('switching providers fences stale catalogs and does not reuse another model’s limit', async ({ page }) => {
  await page.goto('/apps/harness/tests/settings-fixture.html?hold-models')
  await expect.poll(() => page.evaluate(() => window.settingsFixture.requests.length)).toBeGreaterThan(0)
  await chooseOption(page.getByRole('combobox', { name: 'Provider', exact: true }), 'anthropic')
  await expect.poll(() => page.evaluate(() => window.settingsFixture.requests.at(-1).provider)).toBe('anthropic')
  await page.evaluate(() => {
    const f = window.settingsFixture
    f.resolve(f.requests.at(-1).id, { modelInfo: [{ id: 'test-model', contextWindow: 64000 }] })
    for (const r of f.requests.filter((r) => r.provider === 'openai')) f.resolve(r.id, { modelInfo: [{ id: 'test-model', contextWindow: 999999 }] })
  })
  await page.getByRole('combobox', { name: 'Model', exact: true }).fill('test-model')
  await expect(page.getByText(/Provider reports 64,000/)).toBeVisible()
  await page.getByRole('button', { name: 'Save defaults' }).click()
  expect(await page.evaluate(() => window.settingsFixture.saves.at(-1)['max-context'])).toBe(64000)
  await page.getByRole('combobox', { name: 'Model', exact: true }).fill('unknown-model')
  await page.getByRole('button', { name: 'Save defaults' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1)['max-context'])).toBe(defaultConfig()['max-context'])
})

for (const surface of ['global', 'conversation']) {
  test(`${surface}: auth owns the OpenAI endpoint and only Custom can edit one`, async ({ page }) => {
    await page.goto(`/apps/harness/tests/settings-fixture.html?page=${surface}&device`)
    await expect(page.getByLabel('Endpoint', { exact: true })).toHaveCount(0)
    await chooseOption(page.getByRole('combobox', { name: 'Provider', exact: true }), 'openrouter')
    await chooseOption(page.getByRole('combobox', { name: 'Provider', exact: true }), 'openai')
    await expect(page.getByRole('combobox', { name: 'Authentication', exact: true })).toHaveText('Device login (ChatGPT)')
    await expect.poll(() => page.evaluate(url => window.settingsFixture.requests.some(request => request.url === url), PROVIDERS.openai.deviceModelsEndpoint)).toBe(true)
    const save = page.getByRole('button', { name: surface === 'global' ? 'Save defaults' : 'Save conversation' })
    await save.click()
    await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1).url)).toBe(PROVIDERS.openai.deviceEndpoint)
    await page.reload()
    await expect(page.getByRole('combobox', { name: 'Authentication', exact: true })).toHaveText('Device login (ChatGPT)')
    await chooseOption(page.getByRole('combobox', { name: 'Authentication', exact: true }), 'api-key')
    await save.click()
    await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1).url)).toBe(PROVIDERS.openai.endpoint)
    await chooseOption(page.getByRole('combobox', { name: 'Provider', exact: true }), 'openrouter')
    await chooseOption(page.getByRole('combobox', { name: 'Provider', exact: true }), 'openrouter')
    await chooseOption(page.getByRole('combobox', { name: 'Provider', exact: true }), 'openai')
    await expect(page.getByRole('combobox', { name: 'Authentication', exact: true })).toHaveText('Device login (ChatGPT)')
    await chooseOption(page.getByRole('combobox', { name: 'Provider', exact: true }), 'custom')
    await page.getByLabel('Endpoint', { exact: true }).fill('https://inference.example/v1/chat/completions')
    await page.getByRole('combobox', { name: 'Model', exact: true }).fill('custom-model')
    await save.click()
    await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1).url)).toBe('https://inference.example/v1/chat/completions')
  })
}

for (const failSave of [false, true]) test(`device login saves its route and survives reload${failSave ? ' after recovering from a configuration save failure' : ' without a second Save'}`, async ({ page, context }) => {
  await context.route('https://auth.openai.com/**', async (route) => {
    const path = new URL(route.request().url()).pathname
    const payload = path.endsWith('/usercode') ? { device_auth_id: 'fixture', user_code: 'ABCD-EFGH', interval: 2 }
      : path.endsWith('/deviceauth/token') ? { authorization_code: 'fixture-code', code_verifier: 'fixture-verifier' }
        : { access_token: 'fixture-access-token', refresh_token: 'fixture-refresh', id_token: `e30.${Buffer.from(JSON.stringify({ chatgpt_account_id: 'fixture-account' })).toString('base64url')}.signature` }
    await route.fulfill({ json: payload })
  })
  await page.goto('/apps/harness/tests/settings-fixture.html?page=provider')
  await chooseOption(page.getByRole('combobox', { name: 'Authentication', exact: true }), 'device')
  await expect(page.getByLabel('API key', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Endpoint', { exact: true })).toHaveCount(0)
  if (failSave) await page.evaluate(() => { window.settingsFixture.failSave = true })
  await page.getByRole('button', { name: 'Sign in with device code' }).click()
  await page.getByRole('combobox', { name: 'Model', exact: true }).fill('gpt-fixture-selected')
  if (failSave) {
    await expect(page.getByText('Configuration save failed in fixture')).toBeVisible()
    await expect(page.getByText('connected', { exact: true })).toHaveCount(0)
    expect(await page.evaluate(() => window.settingsFixture.saves.length)).toBe(0)
    await page.evaluate(() => { window.settingsFixture.failSave = false })
    await expect(page.getByText('credential configured', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Save OpenAI' }).click()
  }
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1)?.url)).toBe(PROVIDERS.openai.deviceEndpoint)
  expect(await page.evaluate(() => window.settingsFixture.saves.at(-1).model)).toBe('gpt-fixture-selected')
  expect(await page.evaluate(() => window.settingsFixture.credentials)).toEqual(['openai-device'])
  expect(await page.evaluate(() => window.settingsFixture.deviceBundle)).toEqual({ hasRefresh: true, hasAccount: true })
  expect(await page.evaluate(() => window.settingsFixture.saves.at(-1).headers)).toEqual([])
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Authentication', exact: true })).toHaveText('Device login (ChatGPT)')
  await expect(page.getByText('credential configured', { exact: true })).toBeVisible()
  await chooseOption(page.getByRole('combobox', { name: 'Authentication', exact: true }), 'api-key')
  await page.getByLabel('API key', { exact: true }).fill('sk-fixture-api')
  await page.getByRole('button', { name: 'Save OpenAI' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsFixture.saves.at(-1).url)).toBe(PROVIDERS.openai.endpoint)
  expect(await page.evaluate(() => window.settingsFixture.credentials)).toEqual(['openai'])
})
