import { expect, test } from '@playwright/test'

test('work can be created and updated without a project', async ({ page }) => {
  await page.goto('/apps/harness/tests/workspace-fixture.html#/tasks')
  await page.getByRole('button', { name: 'New task', exact: true }).click()
  await page.getByRole('textbox', { name: 'Task title', exact: true }).fill('Check the forecast')
  await page.getByRole('button', { name: 'Create task', exact: true }).click()
  const row = page.locator('.work-task').filter({ hasText: 'Check the forecast' })
  await expect(row).toBeVisible()
  const task = await page.evaluate(() => Object.values(window.workFixture.db.tasks).find(task => task.title === 'Check the forecast'))
  expect(task.project).toBeNull()
  await page.goto(`/apps/harness/tests/workspace-fixture.html#/tasks/${task.id}`)
  await row.getByRole('button', { name: 'Update task' }).click()
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('done')
  await page.getByRole('textbox', { name: 'Outcome or next step' }).fill('Answered in the conversation.')
  await page.getByRole('button', { name: 'Save task', exact: true }).click()
  await expect(row).toContainText('Answered in the conversation.')
  await expect(row).toContainText('Complete')
  expect(await page.evaluate(() => window.workFixture.calls.some(call => call.action === 'task-claim'))).toBe(false)
})

test('task editing, project moves, and deletion act on the exact record', async ({ page }) => {
  await page.goto('/apps/harness/tests/workspace-fixture.html#/tasks/research')
  await page.getByRole('button', { name: 'Update task', exact: true }).click()
  await page.getByRole('textbox', { name: 'Task title', exact: true }).fill('Check supplies')
  await page.getByRole('textbox', { name: 'Brief and expected result' }).fill('List the missing items.')
  await page.getByRole('combobox', { name: 'Project', exact: true }).selectOption('')
  await page.getByRole('button', { name: 'Save task', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Check supplies', exact: true })).toBeVisible()
  expect(await page.evaluate(() => window.workFixture.db.tasks.research.project)).toBeNull()
  await page.getByRole('button', { name: 'Update task', exact: true }).click()
  await page.getByRole('combobox', { name: 'Project', exact: true }).selectOption('neighborhood')
  await page.getByRole('button', { name: 'Save task', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect(await page.evaluate(() => window.workFixture.db.tasks.research.project)).toBe('neighborhood')
  await page.getByRole('button', { name: 'Update task', exact: true }).click()
  await page.getByRole('button', { name: 'Delete task…', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('does not stop an agent or delete linked documents')
  await page.getByRole('button', { name: 'Keep task', exact: true }).click()
  expect(await page.evaluate(() => !!window.workFixture.db.tasks.research)).toBe(true)
  await page.getByRole('button', { name: 'Delete task…', exact: true }).click()
  await page.getByRole('button', { name: 'Delete task', exact: true }).click()
  await expect(page).toHaveURL(/#\/tasks$/)
  await expect(page.getByRole('heading', { name: 'Check supplies', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => !!window.workFixture.db.projects.neighborhood && !!window.workFixture.db.artifacts.guide)).toBe(true)
})

test('a stale task edit or deletion preserves the task and the draft', async ({ page }) => {
  await page.goto('/apps/harness/tests/workspace-fixture.html#/tasks/research')
  await page.getByRole('button', { name: 'Update task', exact: true }).click()
  await page.getByRole('textbox', { name: 'Task title', exact: true }).fill('My unsaved title')
  await page.evaluate(() => { window.workFixture.db.tasks.research.version++; window.workFixture.changed() })
  await page.getByRole('button', { name: 'Save task', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Task changed')
  await expect(page.getByRole('textbox', { name: 'Task title', exact: true })).toHaveValue('My unsaved title')
  await page.getByRole('button', { name: 'Delete task…', exact: true }).click()
  await page.getByRole('button', { name: 'Delete task', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Task changed')
  expect(await page.evaluate(() => window.workFixture.db.tasks.research.title)).toBe('Gather the practical details')
})
