import { expect, test } from '@playwright/test'

test('uncertain Notes recovery observes without replay and requires an explicit release', async ({ page }) => {
  await page.goto('/apps/harness/tests/workspace-fixture.html#/artifacts/guide')
  await page.getByLabel('Document body · Markdown').fill('Preserve this unsaved draft.')
  await page.evaluate(() => { window.workFixture.pending = { id: '0v1', artifact: 'guide', action: 'artifact-save', uncertain: true }; window.workFixture.changed() })
  await expect(page.getByText('Notes result is uncertain')).toBeVisible()
  await page.getByRole('button', { name: 'Check result again' }).click()
  await page.getByRole('button', { name: 'Stop waiting…', exact: true }).click()
  const release = page.getByRole('button', { name: 'Stop waiting', exact: true })
  await expect(release).toBeDisabled()
  await page.getByRole('checkbox', { name: /I inspected Notes/ }).check()
  await release.click()
  await expect(page.getByText('Notes result is uncertain')).toHaveCount(0)
  await expect(page.getByLabel('Document body · Markdown')).toHaveValue('Preserve this unsaved draft.')
  expect(await page.evaluate(() => window.workFixture.calls.filter((call) => ['artifact-create', 'artifact-save', 'publish'].includes(call.action)))).toEqual([])
})

const open = (page, hash = 'artifacts/guide') => page.goto(`/apps/harness/tests/workspace-fixture.html#/${hash}`)
const writes = (page, action) => page.evaluate((name) => window.workFixture.calls.filter((call) => call.action === name), action)

test('artifact edits save immutable revisions and preserve drafts on conflicts', async ({ page }) => {
  await open(page)
  const body = page.getByLabel('Document body · Markdown')
  await body.fill('My unsaved work')
  await page.evaluate(() => window.workFixture.externalEdit())
  await expect(page.getByText("Revision 2 is newer than your draft's base (1).", { exact: false })).toBeVisible()
  await expect(body).toHaveValue('My unsaved work')
  await expect(page.getByRole('button', { name: 'Save revision', exact: true })).toBeDisabled()
  await page.reload()
  await expect(body).toHaveValue('My unsaved work')
  await page.getByRole('button', { name: 'Save revision', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Saved revision 2.' })).toBeVisible()
  expect((await writes(page, 'artifact-save'))[0].args.base).toBe(1)
  expect(await writes(page, 'publish')).toHaveLength(0)
})

test('failed saves leave the draft editable and show the concrete error', async ({ page }) => {
  await open(page)
  await page.getByLabel('Document body · Markdown').fill('A better body')
  await page.evaluate(() => { window.workFixture.failNext = 'artifact-save' })
  await page.getByRole('button', { name: 'Save revision', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Synthetic save failure')
  await expect(page.getByLabel('Document body · Markdown')).toHaveValue('A better body')
  await expect(page.getByRole('button', { name: 'Save revision', exact: true })).toBeEnabled()
})

test('renaming uses Notes metadata and keeps an unsaved body draft', async ({ page }) => {
  await open(page)
  const body = page.getByLabel('Document body · Markdown')
  await body.fill('Keep this unsaved draft')
  await page.getByRole('button', { name: 'Rename…', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Document title').fill('A new Note title')
  await dialog.getByRole('button', { name: 'Rename Note', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A new Note title', exact: true })).toBeVisible()
  await expect(body).toHaveValue('Keep this unsaved draft')
  expect(await writes(page, 'artifact-save')).toHaveLength(0)
  expect(await writes(page, 'publish')).toHaveLength(0)
  expect(await page.evaluate(() => window.workFixture.db.artifacts.guide.head)).toBe(1)
  await page.getByRole('button', { name: 'Save revision', exact: true }).click()
  expect((await writes(page, 'artifact-save'))[0].args).toMatchObject({ title: 'A new Note title', body: 'Keep this unsaved draft', base: 1 })
})

test('publishing requires exact preview confirmation and saving never republishes', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: 'Publish…', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: 'Publish page', exact: true })).toBeDisabled()
  await expect(page.frameLocator('iframe').getByRole('heading', { name: 'A Saturday with the neighbors' })).toBeVisible()
  await dialog.getByLabel('I reviewed revision 1', { exact: false }).check()
  await dialog.getByRole('button', { name: 'Publish page', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: 'Page published' })).toBeVisible()
  expect((await writes(page, 'publish'))[0].args).toMatchObject({ revision: 1, head: 1, exposure: 0, confirm: 'guide@1' })
  await dialog.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByLabel('Document body · Markdown').fill('Private edits after publication')
  await page.getByRole('button', { name: 'Save revision', exact: true }).click()
  await expect(page.getByText('Last published here: revision 1.', { exact: false })).toBeVisible()
  expect(await writes(page, 'publish')).toHaveLength(1)
  await page.getByRole('button', { name: 'Unpublish…', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Unpublish page', exact: true }).click()
  await expect(page.getByText('Public page in Notes', { exact: true })).toHaveCount(0)
})

test('agent proposals expose the exact body difference and accept without publishing', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: 'Proposals', exact: true }).click()
  await page.getByRole('button', { name: /A Saturday with the neighbors.*neighborhood-research/ }).click()
  await expect(page.getByRole('heading', { name: 'Removed', exact: true })).toBeVisible()
  await expect(page.locator('.diff-added')).toContainText('Label dishes with their ingredients.')
  await page.getByRole('button', { name: 'Accept exact changes', exact: true }).click()
  await expect(page.getByText('Accepted as revision 2.', { exact: false })).toBeVisible()
  expect(await writes(page, 'review')).toHaveLength(1)
  expect(await writes(page, 'publish')).toHaveLength(0)
})

test('stale proposals cannot be accepted and new agent drafts start in review', async ({ page }) => {
  await open(page)
  await page.evaluate(() => window.workFixture.externalEdit())
  await page.getByRole('button', { name: 'Proposals', exact: true }).click()
  await page.getByRole('button', { name: /A Saturday with the neighbors.*neighborhood-research/ }).click()
  await expect(page.getByRole('button', { name: 'Accept exact changes', exact: true })).toBeDisabled()
  await open(page, 'artifacts/draft')
  await expect(page.getByRole('heading', { name: 'Review the first draft' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Publish…', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Review proposals', exact: true }).click()
  await page.getByRole('button', { name: /A plan for the afternoon.*neighborhood-research/ }).click()
  await page.getByRole('button', { name: 'Accept exact changes', exact: true }).click()
  await expect(page.getByText('Accepted as revision 1.', { exact: false })).toBeVisible()
})

test('sharing copies one saved revision, with an explicit project confirmation', async ({ page }) => {
  await open(page, 'artifacts/private')
  await page.getByRole('button', { name: 'Copy saved revision to project…' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('combobox', { name: 'Project', exact: true }).selectOption('neighborhood')
  await expect(dialog.getByRole('button', { name: 'Copy and share revision' })).toBeDisabled()
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: 'Copy and share revision' }).click()
  await expect(dialog).toHaveCount(0)
  const [copy] = await writes(page, 'artifact-create')
  expect(copy.args.project).toBe('neighborhood')
  expect(copy.args.body).toBe('Private draft not intended for project members.')
  expect(copy.args.id).not.toBe('private')
  expect(await writes(page, 'artifact-save')).toHaveLength(0)
})

test('project access uses conversation identity and never modifies resource grants', async ({ page }) => {
  await open(page, 'projects/neighborhood')
  await page.getByRole('button', { name: 'Access', exact: true }).click()
  await page.getByRole('combobox', { name: 'Conversation', exact: true }).selectOption('0v2')
  await page.getByRole('combobox', { name: 'Access level', exact: true }).selectOption('contributor')
  await page.getByRole('button', { name: 'Review access…' }).click()
  await expect(page.getByRole('dialog')).toContainText('current and future documents')
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm access' }).click()
  expect((await writes(page, 'member'))[0].args).toEqual({ id: 'neighborhood', version: 1, scope: '0v2', role: 'contributor' })
  await expect(page.getByText('contributor · Workspace tools not enabled', { exact: true })).toBeVisible()
})

test('project task claims and updates carry the current version', async ({ page }) => {
  await open(page, 'projects/neighborhood')
  await page.getByRole('button', { name: 'Tasks', exact: true }).click()
  await page.getByRole('button', { name: 'Claim for myself', exact: true }).click()
  await expect(page.getByText('Claimed by Owner', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Update task', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('combobox', { name: 'Status', exact: true }).selectOption('done')
  await dialog.getByLabel('Outcome or next step').fill('Prepared the guide.')
  await dialog.getByLabel('Result artifact ID (optional)').fill('guide')
  await dialog.getByRole('button', { name: 'Save task' }).click()
  expect((await writes(page, 'task-claim'))[0].args.version).toBe(1)
  expect((await writes(page, 'task-update'))[0].args).toMatchObject({ version: 2, status: 'done', artifact: 'guide' })
  await expect(page.getByRole('link', { name: 'Open result artifact' })).toHaveAttribute('href', '#/artifacts/guide')
})

test('one workspace watch serves the editor and its proposal query without a polling storm', async ({ page }) => {
  await page.clock.install()
  await open(page)
  await page.getByRole('button', { name: 'Proposals', exact: true }).click()
  await page.getByRole('button', { name: /A Saturday with the neighbors.*neighborhood-research/ }).click()
  const count = await page.evaluate(() => window.workFixture.calls.length)
  await page.clock.runFor(60_000)
  expect(await page.evaluate(() => window.workFixture.watchCount())).toBe(1)
  expect((await page.evaluate(() => window.workFixture.calls.length)) - count).toBeLessThanOrEqual(12)
})
